site_name: Monastery Docs
repo_url: https://github.com/arnonmoscona/monastery-docs
site_author: Arnon Moscona
theme: readthedocs
pages:
  - "index.md"
  - "about.md"
  - "domain-model.md"
  - "node.md"
  - "Capabilities.md"
  - "license.md"

